// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzyxccdufqglvejxxlqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6eXhjY2R1ZnFnbHZlanh4bHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzEwNTYsImV4cCI6MjA2MjcwNzA1Nn0.9SLGhZ4hhHwzsngIhyrfibDxcFv2Uq0Z556qkT-F1X4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);